# GitHub Actions workflow.

name: Build and Push Fannotate App Test 

on: push

jobs:

  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 60
    
    steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to phubacrgondor
          uses: TelenorNorgeInternal/gap/docker/login-action@v3
          with:
            username: ${{ secrets.S07601_PHUBACRGONDOR_USERNAME }}
            password: ${{ secrets.S07601_PHUBACRGONDOR_PASSWORD }}
            registry: phubacrgondor.azurecr.io

        - name: Build and push on main
          uses: docker/build-push-action@v4
          with:
            push: true
            load: true
            context: "{{defaultContext}}"
            file: ./Dockerfile
            platforms: linux/amd64
            tags: phubacrgondor.azurecr.io/s07601/fannotate-test:latest
